### PR TITLE
Added a new markdown file for AeroRust docs (Issue#3 Resolution Attempt)

### LINKED ISSUE #3: Content needed - What is AeroRust? Who is it for? What are the benefits of Rust? and more..
We need content to put on the website explaining basic things and answering some questions for newcomers.

Here's a list of things we can include:

- [x] What is the AeroRust community? #10 
- Who is it for? Who can participate? (ofc, everyone, no matter their experience)
- How to join
- How to contribute
- What are the benefits of Rust? - interoperability, memory safety, etc. with articles backing these claims
- [x] Has Rust been to space? (short answer: Yes) Some projects that publicly disclosed this information (CUAVA-1 cubesat is one example: https://www.youtube.com/watch?v=k452kSisfcc&t=72s&ab_channel=AeroRust ) #10 

Things to consider:

- Should we make part of this context as blog posts as well?

### PR DESCRIPTION
**Pull request by prakritishetty**

### CODE REVIEW

**Comment by prakritishetty** [comment]
@elpiel could you have a look at this please?

**Comment by prakritishetty** [comment]
Hi @elpiel , could you please check if this is fine? Actually I'm trying out hacktoberfest, and I really want to be in the 40,000 completing first, hence the slight urgency!

**Comment by elpiel** [comment]
In general looks pretty good. I found a few places that need fixes as well asl a few typos.
I'll make sure to give a better feedback in the coming days.

Thanks you for working on this! It looka great 🤩

**Comment by prakritishetty** [comment]
Oh! Will have a look at the typos till then, sorry!

**Comment by prakritishetty** [comment]
@elpiel I fixed the grammatical errors, please have a look when free!

**Comment by prakritishetty** [comment]
Hi @elpiel any update on this PR?

**Comment by elpiel** [comment]
Yes, I will look into it today

**Comment by elpiel** [comment]
I will merge it as it is but will make it a draft page and make some tweaks.
Thanks for working on the content!

**Comment by prakritishetty** [comment]
Will keep a track of the tweaks and suggest some if anything else strikes me, cheers, thank you!

**Comment by elpiel** [comment]
> Will keep a track of the tweaks and suggest some if anything else strikes me, cheers, thank you!

Thank you.
We are looking to make a good onboarding process and this text might get into the website eventually.

**Review by ranimandira18-hash — APPROVED** [review]

**Pull request merged**
